server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_service
    username: root
    password: 50f1868dfc58e2be473118914ed4cf097d9085b79fa1eb96798fbd32f348e5f6
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: validate | update | create | create-drop | none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


# Actuator configuration for monitoring and management
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints over HTTP

  info:
    env:
      enabled: true  # Include environment information in actuator info endpoint




# configure eureka client

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"


