server:
  port: 9090


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/restaurantdb
    username: user
    password: user123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Options: create, create-drop, validate, none, update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Actuator configuration for monitoring and management
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints over HTTP

  info:
    env:
      enabled: true  # Include environment information in actuator info endpoint

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"



